name: Translate README

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'README.md'

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the workflow to commit the files using your default token
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Auto Translate Markdown
        uses: offensive-vk/auto-translate@master
        with:
          # Your language array (excluding English)
          languages: '["es", "fr", "de", "pt", "ja"]'
          # Finds your root README.md
          files: '["README.md"]'
